server:
  # 服务端===,（最好安装linux版的,windows版的也行,windows版的下载redis的zip包解压后点击redis-server.exe即可）
  port: 8800
#  ssl:
#    key-store: liveforjokes.icu.pfx
#    key-store-password: XF7r4TLs

  connection-timeout: 18000000
spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
  # 数据源（数据库）连接路径及配置属性
  datasource:
    url: jdbc:mysql://8.129.172.254/yiban?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    # Mysql新版本在驱动有改动，建议使用新版驱动配置
    driverClassName: com.mysql.cj.jdbc.Driver
    # 配置阿里的Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的连接数设置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测,并关闭空闲的连接,
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    # 检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jmx:
    enabled: false
  mail:
    username: yiban_snln@163.com
    password: CRKGCELWHXXHJCTG
    host: smtp.163.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

#  http:
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  offset-as-page-num: true
# 日志打印
logging:
  # 路径
  path: logs
  # 日志文件名，如果不配置，默认文件名为spring.log
  file: debug.log
  level:
    # 日志水平，在运行状态下输出日志
    root: info

# Mybatis配置
mybatis-plus:
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    # 默认大小
    default-fetch-size: 100
    # 超时
    default-statement-timeout: 3000
  # 别名
  type-aliases-package: edu.scau.common.mapper

